### ISSUE TITLE
mount-routes 和 newrelic 包一起使用，报错

### ISSUE THREAD

**Issue by hailiang-wang** [moajs/moa#11]
## 启动 newrelic

bin/www

```
  require('newrelic');
```
## 启动 mount-routes

app.js

```
mount(app, __dirname + '/routes', false);
```
## 启动服务

npm start 

过了30秒，报错。

```
octopus/node_modules/mount-routes/index.js:55
    var params = _route.stack.params;
TypeError: Cannot read property 'stack' of undefined
    at _track_routes (octopus/node_modules/mount-routes/index.js:55:24)
    at _use (octopus/node_modules/mount-routes/index.js:46:3)
    at mount (octopus/node_modules/mount-routes/index.js:36:7)
    at mount (octopus/node_modules/mount-routes/index.js:30:7)
    at mount_with_folder (octopus/node_modules/mount-routes/index.js:120:3)
    at Object.<anonymous> (/Users//glory/ai/octopus/app.js:107:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.cls_wrapMethod [as _load] (/ai/octopus/node_modules/newrelic/lib/shimmer
.js:235:38)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/glory/ai/octopus/bin/www:24:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

求 @i5ting 给看看， newrelic 是准备今天新添加的，之前没有这个问题。

**Comment by i5ting** [comment]
好的，收到

**Comment by hailiang-wang** [comment]
这个问题现在还是使用原始办法解决了，写了一个routes进行定义了所有路径。
